version: '2'

services:
  mongo:
    image: mongo:3

  meteor:
    build: app/
    links:
      - mongo
    env_file: config/development/env
    environment:
      MONGO_URL: mongodb://mongo/partup
      ROOT_URL: http://localhost:8080
    ports:
      - "3000:3000"
